name: First_workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greetings
              run: echo "Hello World"
            - name: Print Goodbye
              run: |
                echo "This is my first GitHub Action"
                echo "Workflow executed successfully"
            - name: Display Demo File Content
              run: cat Demo.txt
            - name: List Current Directory
              run: ls -la
            - name: Show Current Date and Time
              run: date
            