name: First_workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greetings
              run: echo "Hello World"
            - name: Print Goodbys
              run: |
                echo "This is my first GitHub Action"
                echo "Workflow executed successfully"